# Generated by Django 6.0.6 on 2026-06-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_slug_alter_blogs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
